# %%
DATA_PATH = "/content/drive/MyDrive/ALT+TAB/data/"

# %%
WIDTH_ORIGINAL = 1280
HEIGHT_ORIGINAL = 720
WIDTH_RESIZE = 640
HEIGHT_RESIZE = 360

DEFAULT_NORMALIZED_WIDTH_FOR_BOX = 0.038
DEFAULT_NORMALIZED_HEIGHT_FOR_BOX = 0.17
